// Provider adapter contract — SKY-463 / GH#210
//
// This module defines the normalized interface every provider adapter must
// satisfy.  No runtime switching or concrete adapter implementations live here
// (those are deferred to a follow-up).  The types are the source of truth that
// fixtures, tests, and future adapters compile against.

import type { ProviderKind } from '../provider.js';

export type { ProviderKind };

// ─── Request shape ────────────────────────────────────────────────────────────

export interface TextContent {
  type: 'text';
  /** Raw text content of this block */
  text: string;
}

export interface ImageContent {
  type: 'image';
  /** Base64-encoded data URI or an https:// URL */
  source: string;
  /** MIME type, e.g. 'image/png'.  Required when source is a data URI. */
  mediaType?: string;
}

/** Structured content block within a message */
export type ContentBlock = TextContent | ImageContent;

export interface ToolDefinition {
  /** Stable name used when the model calls the tool and in tool_use events */
  name: string;
  /** Human-readable purpose shown to the model */
  description?: string;
  /** JSON Schema object describing the tool's input parameters */
  inputSchema: Record<string, unknown>;
}

export interface AdapterMessage {
  role: 'user' | 'assistant';
  /** Plain string or a list of structured content blocks */
  content: string | ContentBlock[];
}

export interface AdapterRequest {
  /** Conversation history in chronological order */
  messages: AdapterMessage[];
  /** System-level instruction prepended to the context */
  system?: string;
  /** Tools the model may call during this turn */
  tools?: ToolDefinition[];
  /** Provider-scoped model identifier, e.g. 'claude-sonnet-4-6' or 'gpt-4o-mini' */
  model: string;
  /** Hard limit on generated tokens.  Provider defaults apply when omitted. */
  maxTokens?: number;
  /** Sampling temperature in [0, 1].  Higher values increase randomness. */
  temperature?: number;
  /** Strings whose appearance halts generation (in addition to end-of-turn) */
  stopSequences?: string[];
  /** Forwarded to fetch / SDK to support cooperative cancellation */
  signal?: AbortSignal;
  /** Invoked once before the request and once after the finish event */
  onLog?: LogHook;
}

// ─── Token accounting ─────────────────────────────────────────────────────────

export interface TokenUsage {
  /** Tokens consumed by the prompt, including tool definitions and history */
  inputTokens: number;
  /** Tokens generated by the model in this turn */
  outputTokens: number;
  /** inputTokens + outputTokens */
  totalTokens: number;
  /** Prompt tokens served from the provider cache (Anthropic-specific; omit for others) */
  cacheReadInputTokens?: number;
  /** Prompt tokens written into the provider cache this turn (Anthropic-specific; omit for others) */
  cacheCreationInputTokens?: number;
}

// ─── Streaming events ─────────────────────────────────────────────────────────

export type StopReason =
  | 'end_turn'       // Model reached a natural stopping point
  | 'max_tokens'     // maxTokens limit was hit
  | 'stop_sequence'  // A stopSequences entry was produced
  | 'tool_use'       // Model invoked a tool; generation resumes after the result
  | 'cancelled'      // AbortSignal fired before end-of-turn
  | 'error';         // Stream ended due to a non-retryable error

/** Incremental text token emitted by the model during generation */
export interface DeltaEvent {
  type: 'delta';
  /** One or more characters of generated text */
  text: string;
}

/**
 * Complete tool invocation once the model has finished assembling the input
 * JSON.  Consumers should collect all delta events before processing tool_use.
 */
export interface ToolUseEvent {
  type: 'tool_use';
  /** Provider-assigned call ID; echoed back in the tool-result message */
  id: string;
  /** Name matching a ToolDefinition in the original request */
  name: string;
  /** Fully-assembled input object for the named tool */
  input: unknown;
}

/** End-of-stream marker.  Always the last event emitted by a healthy stream. */
export interface FinishEvent {
  type: 'finish';
  stopReason: StopReason;
  /** Token accounting for this turn, as reported by the provider */
  usage: TokenUsage;
}

/**
 * Recoverable error event.  Fatal errors are thrown by the generator instead
 * of being yielded so callers catch them naturally with try/catch or for-await.
 */
export interface ErrorEvent {
  type: 'error';
  error: AdapterError;
}

export type StreamEvent = DeltaEvent | ToolUseEvent | FinishEvent | ErrorEvent;

// ─── Error normalization ──────────────────────────────────────────────────────

export type AdapterErrorKind =
  | 'auth'           // 401 / 403 — bad or missing API key
  | 'rate_limit'     // 429 — per-minute or per-day quota exceeded
  | 'context_length' // Prompt + completion exceeds the model's context window
  | 'network'        // fetch / socket failure before any response bytes arrived
  | 'server'         // 5xx from the provider
  | 'malformed';     // Response body could not be parsed as expected

export interface AdapterError {
  /** Normalized category for programmatic retry / display logic */
  kind: AdapterErrorKind;
  /** Human-readable message from the provider, or a synthetic fallback */
  message: string;
  /** True when an exponential-backoff retry is likely to succeed */
  retryable: boolean;
  /** HTTP status code when the error originated from an HTTP response */
  status?: number;
}

// ─── Prompt-history logging ───────────────────────────────────────────────────

export interface LogEntry {
  /**
   * 'request' entries are written immediately before the HTTP call;
   * 'response' entries are written after the FinishEvent is received.
   */
  direction: 'request' | 'response';
  /** Model identifier as sent to the provider */
  model: string;
  /**
   * Message history as transmitted.  Content may be replaced with
   * '[redacted]' by the caller before passing to persistent storage.
   */
  messages: Array<{ role: string; content: string | '[redacted]' }>;
  /** System prompt if present; may be '[redacted]' */
  system?: string | '[redacted]';
  /** Populated on 'response' entries; undefined for 'request' entries */
  usage?: TokenUsage;
  /** Unix timestamp in milliseconds */
  timestampMs: number;
}

/** Receives a sanitizable log record before and after each provider request */
export type LogHook = (entry: LogEntry) => void;

// ─── Adapter interface ────────────────────────────────────────────────────────

/**
 * Contract that every provider adapter must satisfy.
 *
 * The stream() method returns an AsyncGenerator that yields normalized
 * StreamEvents in order: zero or more DeltaEvents, interspersed ToolUseEvents,
 * then exactly one FinishEvent.  Fatal errors are thrown so the caller's
 * for-await-of catches them; non-fatal errors may be yielded as ErrorEvents.
 *
 * Cancellation: when request.signal fires, the generator should clean up
 * (release reader locks, abort in-flight fetches) and yield a FinishEvent
 * with stopReason 'cancelled' before returning, or throw an AbortError.
 */
export interface ProviderAdapter {
  /** Must match the ProviderKind this adapter handles */
  readonly kind: ProviderKind;
  /** Begin streaming a completion; yields normalized events until done */
  stream(request: AdapterRequest): AsyncGenerator<StreamEvent>;
}
