/**
 * fcfb oracle killing rows (groups a–g plus witness cover). Source: rows_fcfb.json.
 * expectedDeleted is canonical under both GFPN models K and W.
 */

export type FcfbOracleEnvName = 'E1' | 'E2' | 'E5' | 'E6';

export type FcfbOracleRow = {
  readonly id: string;
  readonly group: string;
  readonly lines: readonly string[];
  readonly fault: string | null;
  readonly env: FcfbOracleEnvName;
  readonly expectedDeleted: readonly string[];
};

export const SIDECAR_FCFB_ORACLE_ROWS: readonly FcfbOracleRow[] = [
  {
    id: "G2",
    group: "g",
    lines: ["D:\\APPS32\\DOCS\\v\r\n"],
    fault: null,
    env: "E6",
    expectedDeleted: [],
  },
  {
    id: "C18",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\v\\..a\\\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v\\..a\\"],
  },
  {
    id: "C10",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\v\\.. a\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v\\.. a"],
  },
  {
    id: "W:101:reg2:$8->$3",
    group: "w",
    lines: ["C:\\Users\\me\\AppData\\Roaming\\Mythos Writer\r\n", "C:\\Users\\me\\Documents\\..x\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\..x"],
  },
  {
    id: "C11",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\v/.x\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v/.x"],
  },
  {
    id: "B15",
    group: "b",
    lines: ["C:\\Users\\me\\Documents\r\n", "C:\\Users\\me\\Documents\\.x\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\.x"],
  },
  {
    id: "C12",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\v/..x\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v/..x"],
  },
  {
    id: "C3",
    group: "c",
    lines: ["C:\\Users\\me\\Downloads\\v\\.\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "C8",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\v\\...a\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v\\...a"],
  },
  {
    id: "C9",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\v\\. a\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v\\. a"],
  },
  {
    id: "C13",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\v/...a\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v/...a"],
  },
  {
    id: "C14",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\v/. a\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v/. a"],
  },
  {
    id: "C15",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\v/.. a\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v/.. a"],
  },
  {
    id: "C27",
    group: "c",
    lines: ["C:\\Users\\me\\Downloads\\v./\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "C29",
    group: "c",
    lines: ["C:\\Users\\me\\Downloads\\v /\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "C31",
    group: "c",
    lines: ["C:\\Users\\me\\Downloads\\v/ \r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "C33",
    group: "c",
    lines: ["C:\\Users\\me\\Downloads\\v\\./\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "C35",
    group: "c",
    lines: ["C:\\Users\\me\\Downloads\\v/.\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "C37",
    group: "c",
    lines: ["C:\\Users\\me\\Downloads\\v/./\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "C39",
    group: "c",
    lines: ["C:\\Users\\me\\Downloads\\v/.\\\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "C45",
    group: "c",
    lines: ["C:\\Users\\me\\Downloads\\a/b/..\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "F1zero",
    group: "f",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\z\r\n"],
    fault: "g1zero@2",
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "W:87:tgt3:uninstall_vault_read->mythos_canon_gate",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v\\.. .\\x\r\n", "C:\\Users\\me\\Documents\\ok2\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok", "C:\\Users\\me\\Documents\\ok2"],
  },
  {
    id: "W:92:tgt3:uninstall_vault_read->mythos_canon_gate",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v\\ x/../../Windows\r\n", "C:\\Users\\me\\Documents\\ok2\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok", "C:\\Users\\me\\Documents\\ok2"],
  },
  {
    id: "B1",
    group: "b",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\b.\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "B4",
    group: "b",
    lines: ["x\r\n", "C:\\Users\\me\\Documents\\a\u0001b\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "B9",
    group: "b",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\/v\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S3",
    group: "s",
    lines: ["C:\\Users\\me\\Desktop\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S4",
    group: "s",
    lines: ["C:\\Users\\me\\Downloads\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S5",
    group: "s",
    lines: ["C:\\Users\\me\\Documents\\\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S6",
    group: "s",
    lines: ["C:\\Users\\me\\AppData\\Roaming\\Mythos Writer\\\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S7",
    group: "s",
    lines: ["C:\\Users\\me\\Desktop\\\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S8",
    group: "s",
    lines: ["C:\\Users\\me\\Downloads\\\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S9",
    group: "s",
    lines: ["C:\\Users\\me\\AppData\\Roaming\\Mythos Writerx\\y\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S10",
    group: "s",
    lines: ["C:\\Users\\me\\Desktop/v\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S11",
    group: "s",
    lines: ["C:\\Users\\me\\Downloads/v\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S15",
    group: "s",
    lines: ["C:\\Users\\me\\Documents\\../Windows\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S17",
    group: "s",
    lines: ["C:\\Users\\me\\Documents\\v/..\\x\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S18",
    group: "s",
    lines: ["C:\\Users\\me\\Documents\\..\n\\x\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "C19",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\v/..a/\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v/..a/"],
  },
  {
    id: "C21",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\v/..a\\\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v/..a\\"],
  },
  {
    id: "F1trunc",
    group: "f",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\z\r\n"],
    fault: "g1trunc@2",
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "F1truncP",
    group: "f",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\z\r\n"],
    fault: "g1truncP@2",
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "F2zero1",
    group: "f",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\z\r\n"],
    fault: "g2zero@1",
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\z"],
  },
  {
    id: "F2trunc1",
    group: "f",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\z\r\n"],
    fault: "g2trunc@1",
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\z"],
  },
  {
    id: "F2truncP1",
    group: "f",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\z\r\n"],
    fault: "g2truncP@1",
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\z"],
  },
  {
    id: "W:97:tgt3:uninstall_vault_read->mythos_canon_gate",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v\\.\r\n", "C:\\Users\\me\\Documents\\ok2\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok", "C:\\Users\\me\\Documents\\ok2"],
  },
  {
    id: "W:98:tgt3:uninstall_vault_read->uninstall_vault_close",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v\\.\\x\r\n", "C:\\Users\\me\\Documents\\ok2\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok", "C:\\Users\\me\\Documents\\ok2"],
  },
  {
    id: "W:105:reg1:$4->$2",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\v\\..a/\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\v\\..a/"],
  },
  {
    id: "W:112:tgt3:uninstall_vault_read->mythos_canon_gate",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v/.. ./x\r\n", "C:\\Users\\me\\Documents\\ok2\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok", "C:\\Users\\me\\Documents\\ok2"],
  },
  {
    id: "W:118:tgt3:uninstall_vault_read->mythos_canon_gate",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v/ x/../../Windows\r\n", "C:\\Users\\me\\Documents\\ok2\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok", "C:\\Users\\me\\Documents\\ok2"],
  },
  {
    id: "W:123:tgt3:uninstall_vault_read->mythos_canon_gate",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v/.\r\n", "C:\\Users\\me\\Documents\\ok2\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok", "C:\\Users\\me\\Documents\\ok2"],
  },
  {
    id: "W:124:tgt3:uninstall_vault_read->mythos_canon_gate",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v/./x\r\n", "C:\\Users\\me\\Documents\\ok2\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok", "C:\\Users\\me\\Documents\\ok2"],
  },
  {
    id: "A1",
    group: "a",
    lines: ["C:\\Users\\me\\Documents\\v\\.:\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "A2",
    group: "a",
    lines: ["C:\\Users\\me\\Documents\\v/.:\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "B2",
    group: "b",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\b \r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "B7",
    group: "b",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\a\\b\\..\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "B8",
    group: "b",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\a/b/..\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "B10",
    group: "b",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\./Windows\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "B11",
    group: "b",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\x\\..\\v\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "B12",
    group: "b",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v/.\\x\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "B13",
    group: "b",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v/../x\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "B17",
    group: "b",
    lines: ["C:\\Users\\me\\Desktop\\ok\r\n", "C:\\Users\\me\\Desktop\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Desktop\\ok", "C:\\Users\\me\\Desktop\\ok"],
  },
  {
    id: "B18",
    group: "b",
    lines: ["C:\\Users\\me\\Downloads\\ok\r\n", "C:\\Users\\me\\Downloads\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Downloads\\ok", "C:\\Users\\me\\Downloads\\ok"],
  },
  {
    id: "B19",
    group: "b",
    lines: ["C:\\Users\\me\\AppData\\Roaming\\Mythos Writer\\ok\r\n", "C:\\Users\\me\\AppData\\Roaming\\Mythos Writer\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\AppData\\Roaming\\Mythos Writer\\ok", "C:\\Users\\me\\AppData\\Roaming\\Mythos Writer\\ok"],
  },
  {
    id: "S1",
    group: "s",
    lines: ["C:\\Users\\me\\Documents\\/v\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S12",
    group: "s",
    lines: ["C:\\Program Files (x86)\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S13",
    group: "s",
    lines: ["C:\\Users\\me\\Documents\\v.\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S14",
    group: "s",
    lines: ["C:\\Users\\me\\Documents\\./Windows\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "S16",
    group: "s",
    lines: ["C:\\Users\\me\\Documents\\v/.\\x\r\n", "C:\\Users\\me\\Documents\\ok\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "C22",
    group: "c",
    lines: ["C:\\Users\\me\\Documents\\vx/\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\vx/"],
  },
  {
    id: "C23",
    group: "c",
    lines: ["C:\\Users\\me\\AppData\\Roaming\\Mythos Writer\\x\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\AppData\\Roaming\\Mythos Writer\\x"],
  },
  {
    id: "C24",
    group: "c",
    lines: ["C:\\Users\\me\\Desktop\\x\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Desktop\\x"],
  },
  {
    id: "C25",
    group: "c",
    lines: ["C:\\Users\\me\\Downloads\\x\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Downloads\\x"],
  },
  {
    id: "G5",
    group: "g",
    lines: ["C:\\Users\\me\\Desktop\\My Vault\r\n"],
    fault: null,
    env: "E6",
    expectedDeleted: ["C:\\Users\\me\\Desktop\\My Vault"],
  },
  {
    id: "G6",
    group: "g",
    lines: ["C:\\Users\\pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\\Documents\\vvvvvvvvvvvvvvvvvvvv\r\n"],
    fault: null,
    env: "E5",
    expectedDeleted: ["C:\\Users\\pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\\Documents\\vvvvvvvvvvvvvvvvvvvv"],
  },
  {
    id: "H5",
    group: "d",
    lines: ["\\??\\C:\\Users\\pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\\AppData\\Roaming\\Mythos Writer\r\n"],
    fault: null,
    env: "E5",
    expectedDeleted: [],
  },
  {
    id: "H6",
    group: "d",
    lines: ["C:\\Users\\pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\\Documentsx\\v\r\n"],
    fault: null,
    env: "E5",
    expectedDeleted: [],
  },
  {
    id: "H7",
    group: "d",
    lines: ["C:\\Users\\pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\\Desktop/v\r\n"],
    fault: null,
    env: "E5",
    expectedDeleted: [],
  },
  {
    id: "H8",
    group: "d",
    lines: ["C:\\Users\\pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\\Downloadsx\\v\r\n"],
    fault: null,
    env: "E5",
    expectedDeleted: [],
  },
  {
    id: "H1",
    group: "d",
    lines: ["C:\\Users\\me\\Documents\\a/./../Windows\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "H2",
    group: "d",
    lines: ["C:\\Users\\me\\Documents\\v/.\\..\\..\\Windows\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "H3",
    group: "d",
    lines: ["C:\\Users\\me\\Documents\\v/..\\..\\..\\Windows\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: [],
  },
  {
    id: "F1zero1",
    group: "f",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\z\r\n"],
    fault: "g1zero@1",
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\z"],
  },
  {
    id: "F1trunc1",
    group: "f",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\z\r\n"],
    fault: "g1trunc@1",
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\z"],
  },
  {
    id: "F1truncP1",
    group: "f",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\z\r\n"],
    fault: "g1truncP@1",
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\z"],
  },
  {
    id: "W:105:tgt3:uninstall_vault_read->mythos_canon_gate",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v\\../Windows\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
  {
    id: "W:113:tgt3:uninstall_vault_read->uninstall_vault_close",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v\\.. /Windows\r\n", "C:\\Users\\me\\Documents\\ok2\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok", "C:\\Users\\me\\Documents\\ok2"],
  },
  {
    id: "W:129:tgt3:uninstall_vault_read->mythos_canon_gate",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v/..\r\n", "C:\\Users\\me\\Documents\\ok2\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok", "C:\\Users\\me\\Documents\\ok2"],
  },
  {
    id: "W:131:tgt3:uninstall_vault_read->mythos_canon_gate",
    group: "w",
    lines: ["C:\\Users\\me\\Documents\\ok\r\n", "C:\\Users\\me\\Documents\\v/..\\x\r\n"],
    fault: null,
    env: "E1",
    expectedDeleted: ["C:\\Users\\me\\Documents\\ok"],
  },
];

